services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ultimatelibrary
    volumes:
      - ultimatelibrary:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  ultimatelibrary: